### ISSUE TITLE
Initial version(s)

### ISSUE THREAD

**Issue by rhattersley** [SciTools/libmo_unpack#13]
For our first GitHub based release:
- What interface version do we want? (e.g. 3:0:0) The section "The Libtool library versioning scheme" in this [guide to building shared libraries](http://www.freesoftwaremagazine.com/articles/building_shared_libraries_once_using_autotools) has good explanation.
- What (if any?) release version do we want? (e.g. libmo_unpack v0.2.0)

**Comment by marqh** [comment]
https://github.com/SciTools/conda-recipes-scitools/blob/master/libmo_unpack/meta.yaml
has a version of 

```
    version: !!str 2.0.3
```

which is derived from
puma, thus https://github.com/SciTools/libmo_unpack/releases/tag/PUMA-160114
it would be good to have a version which is deemed 'newer' than that

**Comment by rhattersley** [comment]
> it would be good to have a version which is deemed 'newer' than that

Agreed. (Technically that's the conda version which is independent ... but I'd **_far**_ rather we kept them in sync if possible!)

**Comment by rhattersley** [comment]
Previous releases didn't honour the libtool version convention (they [mistakenly treated it as major:minor:rel](https://github.com/SciTools/libmo_unpack/blob/b69437550a9c05ab7bde5c6a66f995ad51380dd3/make_library#L110)). I suggest we increment the interface version to 3 (specifically 3:0:0) to avoid ambiguity.

**Comment by marqh** [comment]
> Previous releases didn't honour the libtool version convention (they mistakenly treated it as major:minor:rel). I suggest we increment the interface version to 3 (specifically 3:0:0) to avoid ambiguity.

i agree; it makes a clear statement of change
