### ISSUE TITLE
Remove logging in release build

### ISSUE THREAD

**Issue by rhattersley** [SciTools/libmo_unpack#5]
For a x50 speedup, get rid of all the `MO_syslog` and `snprintf` calls when doing a release build.

For example: https://github.com/SciTools/conda-recipes-scitools/blob/3ef7098ac153a5aa86cab3371a57ec2e87b0fd40/libmo_unpack/speedup.patch

**Comment by pelson** [comment]
:+1: 
Incidentally, that patch came from <30mn work. It would not surprise me if there was more to be squeezed-out with little effort. (I think we are all clear that there is no interest in a more substantial re-write at this stage)

**Comment by rhattersley** [comment]
Fixed by #11
